name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        cd testCabal
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: |
        cd testCabal
        cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: |
        cd testCabal
        cabal run all
