name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        cabal: ["3.4"]
        ghc: ["9.0.1"]
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v1.2
    - run: cabal v2-update
    - run: cabal v2-build
    - run: cabal v2-test
